# Generated by Django 4.0.6 on 2022-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='link',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
