# Generated by Django 4.0.6 on 2022-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_author_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
